<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- 1. Enlace directo al Padre de la Hashimoto Platform -->
    <parent>
        <groupId>com.hashimoto.platform</groupId>
        <artifactId>hashimoto-platform-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath> <!-- Sube un nivel para heredar del centro de mandos -->
    </parent>

    <artifactId>api-gateway</artifactId>
    <name>api-gateway</name>
    <description>API Gateway de la Plataforma basado en Spring Cloud Gateway</description>

    <dependencies>
        <!-- 2. Spring Cloud Gateway (Entorno Reactivo Netty) -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>

        <!-- 3. Seguridad Perimetral Core -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>

        <!-- 4. Servidor de Recursos (Necesario para validar los tokens JWT de Keycloak) -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
        </dependency>

        <!-- 5. Cliente OAuth2 (¡INDISPENSABLE! Activa la fábrica del filtro TokenRelay) -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-client</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Plugin de empaquetado heredado de la configuración del Padre -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>

