services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: hashimoto-keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - "8082:8080" # <-- Puerto 8082 en tu máquina física Keycloak en el puerto 8080 (dentro de la red interna de Docker) y exponerlo hacia afuera en tu máquina local en el puerto 8082
    volumes:
      # 2. MAPEAMOS TU CONFIGURACIÓN AL CONTENEDOR 📁
      # Vincula tu carpeta local con la carpeta interna donde Keycloak busca los JSON para importar
      - ./keycloak-config:/opt/keycloak/data/import:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - platform-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - platform-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - platform-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - platform-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - platform-network

  postgres:
    image: postgres:16
    container_name: patient-postgres
    environment:
      POSTGRES_DB: patient_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data # 👈 AGREGA ESTO para que los datos de Postgres nunca se borren
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d patient_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - platform-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
        - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - platform-network

  patient-service:
    build:
      context: . # 💥 CONTEXTO EN LA RAÍZ GLOBAL: Así puede leer el POM Padre
      dockerfile: patient-service/Dockerfile # Ruta exacta desde la raíz
    container_name: patient-service
    user: "1000:1000"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./patient_logs:/app/app/logs # 📁 Montar la carpeta de logs en /app/app/logs para que coincida con la ruta usada por las apps
    networks:
      - platform-network

  api-gateway:
    build:
      context: . # 💥 CONTEXTO EN LA RAÍZ GLOBAL: Para heredar del padre
      dockerfile: api-gateway/Dockerfile # Ruta exacta desde la raíz
    container_name: api-gateway
    user: "1000:1000"
    ports:
      - "8081:8081"
    depends_on:
      keycloak:
        condition: service_started
    volumes:
      - ./patient_logs:/app/app/logs # 📁 Montar la carpeta de logs en /app/app/logs para que coincida con la ruta usada por las apps
    networks:
      - platform-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0
    container_name: filebeat
    user: "1000:1000"
    command: [ "--strict.perms=false" ]
    volumes:
      - ./patient_logs:/app/app/logs # 📁 Montar la carpeta de logs en /app/app/logs para que coincida con la ruta usada por las apps
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - platform-network

volumes:
  esdata:
  patient_logs:
  postgres_data: # 👈 AGREGA ESTO para que los datos de Postgres nunca se borren

networks:
  platform-network:
    driver: bridge # Crea una red interna tipo puente para interconectar los contenedores
