filebeat.inputs:
  - type: filestream
    id: patient-service-logs
    enabled: true # 👈 ¡OBLIGATORIO para activar la lectura!
    paths:
      - /app/logs/*.log # 🔒 Ruta única y consistente: host ./logs -> contenedor /app/logs

    # Agrupa los errores multilínea de Java para que no salgan rotos en Kibana
    parsers:
      - multiline:
          type: pattern
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
          negate: true
          match: after

# Configuración corporativa de índices para Elasticsearch
setup.ilm.enabled: false
setup.template.name: "logs"
setup.template.pattern: "logs-*"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "logs-%{+yyyy.MM.dd}" # Estructura tus índices por día
