# El Orquestador punta a una imagen local llamada hashimoto/api-gateway:latest
#e incluirá también el volumen de logs para evitar el mismo problema que sufrió el servicio de pacientes.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: hashimoto-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: hashimoto/api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: LOG_PATH
              value: "/app/logs/api-gateway.log"
            - name: KEYCLOAK_ISSUER_URI
              value: "http://localhost/auth/realms/hashimoto-realm"
            - name: KEYCLOAK_JWK_SET_URI
              value: "http://cluster.local"

#          # 🩺 NUEVO: Sondas de salud automáticas para el Gateway (Puerto 8081)
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8081
#            initialDelaySeconds: 90 # Le da 30 segundos a Spring Boot para arrancar antes de empezar a medir
#            periodSeconds: 15       # Revisa el corazón de la app cada 10 segundos\
#            failureThreshold: 4     # Le permite fallar hasta 4 veces antes de matarlo
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8081
#            initialDelaySeconds: 90
#            periodSeconds: 15
#
          volumeMounts:
            - name: app-logs
              mountPath: /app/logs
      volumes:
        - name: app-logs
          emptyDir: {}
