server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://patient-service:8080 # 👈 URL interna de la red de Docker
          predicates:
            - Path=/api/patients/**
          filters:
            - TokenRelay=

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/hashimoto-realm # 👈 Puerto interno 8080
          jwk-set-uri: http://keycloak:8080/realms/hashimoto-realm/protocol/openid-connect/certs

logging:
  file:
    # 💥 Si no hay variable local, Docker guardará el archivo en /app/logs/api-gateway.log
    name: ${LOG_PATH:"/app/logs/api-gateway.log}"