server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://patient-service:8080 # 👈 URL interna de la red de Docker
          predicates:
            - Path=/api/patients/**
          filters:
            - TokenRelay=

  security:
    oauth2:
      resourceserver:
        jwt:
          # 1. El Emisor esperado: Coincide con lo que firmó tu navegador afuera en tu PC
          issuer-uri: http://localhost:8082/realms/hashimoto-realm

          # 2. Dirección interna de Docker: Usa el host "keycloak" y el puerto interno "8080"
          jwk-set-uri: http://keycloak:8080/realms/hashimoto-realm/protocol/openid-connect/certs

logging:
  file:
    # Ruta definitiva: siempre /app/logs/... dentro del contenedor
    name: ${LOG_PATH:/app/logs/api-gateway.log}

management:
  endpoints:
    web:
      exposure:
        # Expone solo los endpoints necesarios por seguridad (Health y Prometheus)
        include: "health,prometheus"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      # Añade el nombre del microservicio automáticamente a cada métrica
      application: ${spring.application.name}