spring.application.name=patient-service

# Desactivar la búsqueda automática de Axon Server
axon.axonserver.enabled=false

# Configuración por defecto orientada a la red de Docker Compose
spring.datasource.url=jdbc:postgresql://localhost:5432/patient_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=kafka:29092
