# Sobrescribe las URLs de Docker para desarrollo local en tu IDE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patient_db
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          # 🔐 REQUERIDO POR TU CLASE SECURITYCONFIG
          issuer-uri: http://localhost:8082/realms/hashimoto-realm
          jwk-set-uri: http://localhost:8080/realms/hashimoto-realm/protocol/openid-connect/certs

axon:
  kafka:
    bootstrap-servers: localhost:9092

# Opcional: Detalle de logs para auditar Axon y Seguridad
logging:
  level:
    org.springframework.security: DEBUG
    org.axonframework: INFO

# 💥 Define la ruta física externa para el volumen compartido de tus logs
LOG_PATH: "../logs/api-gateway.log"