spring.application.name=patient-service

# Desactivar la búsqueda automática de Axon Server
axon.axonserver.enabled=false

# Configuración de base de datos orientada a la red de Docker
spring.datasource.url=jdbc:postgresql://postgres:5432/patient_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Infraestructura unificada de Kafka en Docker
spring.kafka.bootstrap-servers=kafka:29092
axon.kafka.bootstrap-servers=kafka:29092

# Configuración del Productor de Eventos de Axon hacia Kafka
axon.kafka.producer.event-processor-mode=subscribing
axon.kafka.default-topic=patient-events

# Serializadores obligatorios para enviar bytes a Kafka
axon.kafka.properties.key.serializer=org.apache.kafka.common.serialization.StringSerializer
axon.kafka.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
# Forzar a Spring Boot a levantar el servidor web Tomcat
spring.main.web-application-type=servlet