# Sobrescribe las URLs de Docker para desarrollo local en tu IDE
spring.datasource.url=jdbc:postgresql://localhost:5432/patient_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.kafka.bootstrap-servers=localhost:9092
axon.kafka.bootstrap-servers=localhost:9092

# 🔐 AGREGAR ESTA LÍNEA REQUERIDA POR TU CLASE SECURITYCONFIG:
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/hashimoto-realm