# Permisos Especiales y Orquestador: k8s/monitoring/logging/filebeat.yaml
# Como Filebeat necesita meterse a las entrañas del sistema operativo de los nodos para leer los archivos de log globales,
# requiere permisos de administración avanzados (RBAC). Le daremos una identidad segura (ServiceAccount) y lo desplegaremos como un DaemonSet.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-sa
  namespace: hashimoto-logs
  labels:
    k8s-app: filebeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-cluster-role
  labels:
    k8s-app: filebeat
rules:
  - apiGroups: [""] # "" indica el core API group
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - watch
      - list
  - apiGroups: ["apps"]
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: filebeat-sa
    namespace: hashimoto-logs
roleRef:
  kind: ClusterRole
  name: filebeat-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet # 👈 ¡El estándar profesional para recolectores!
metadata:
  name: filebeat
  namespace: hashimoto-logs
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      serviceAccountName: filebeat-sa
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.15.0
          args: [
            "-c", "/usr/share/filebeat/filebeat.yml",
            "-e",
          ]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0 # Requiere root temporal únicamente para engancharse a los sockets de log del sistema
          volumeMounts:
            - name: config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
              readOnly: true
            - name: varlogcontainers
              mountPath: /var/log/containers
              readOnly: true
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config
          configMap:
            defaultMode: 0640
            name: filebeat-config
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
